# Generated by Django 4.1.5 on 2023-01-07 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorphedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='original/')),
                ('image2', models.ImageField(upload_to='original/')),
                ('morphedimage', models.ImageField(upload_to='morphed/')),
                ('data', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_morphed_images', to='userapp.usermodel')),
            ],
            options={
                'db_table': 'morphed_images',
            },
        ),
    ]
