# Generated by Django 4.1.5 on 2023-01-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_morphedimages_morphedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_image', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'image_analysis',
            },
        ),
    ]
