# Generated by Django 4.1.5 on 2023-01-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_imageanalysismodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('picture', models.ImageField(upload_to='uploads/')),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('marital_status', models.CharField(max_length=15)),
                ('citizenship_by', models.CharField(max_length=25)),
                ('education', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'application_details',
            },
        ),
    ]
