# Generated by Django 4.1.5 on 2023-01-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_applicationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
