# Generated by Django 4.1.5 on 2023-01-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_applicationmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='citizenship_by',
            field=models.CharField(max_length=50),
        ),
    ]
