# Generated by Django 4.1.5 on 2023-01-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_applicationmodel_citizenship_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='morphedimages',
            name='image3',
            field=models.ImageField(null=True, upload_to='original/'),
        ),
    ]
